# Generated by Django 2.2.6 on 2019-10-31 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('cond', '0001_initial'),
	]

	operations = [
		migrations.CreateModel(
			name='RiegoParam',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('start_date', models.DateTimeField()),
				('end_date', models.DateTimeField()),
				('water_time', models.IntegerField()),
				('is_active', models.BooleanField()),
			],
		),
		migrations.CreateModel(
			name='Riego',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('date', models.DateTimeField(auto_now_add=True)),
				('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
			],
		),
	]
