# Generated by Django 2.0.7 on 2018-07-27 07:43

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		('cond', '0001_initial'),
	]

	operations = [
		migrations.AlterField(
			model_name='user',
			name='telefono',
			field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
		),
	]
