# Generated by Django 2.0.7 on 2018-07-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cond', '0002_auto_20180727_0343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arduino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadena', models.CharField(max_length=10)),
            ],
        ),
    ]
