# Generated by Django 2.2.6 on 2019-10-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('cond', '0002_riego_riegoparam'),
	]

	operations = [
		migrations.CreateModel(
			name='Bombillo',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('categoria', models.CharField(max_length=5)),
				('status', models.BooleanField()),
			],
		),
		migrations.AlterField(
			model_name='riegoparam',
			name='is_active',
			field=models.BooleanField(blank=True),
		),
		migrations.AlterField(
			model_name='riegoparam',
			name='water_time',
			field=models.IntegerField(blank=True),
		),
	]
