# Generated by Django 2.0.7 on 2018-08-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('cond', '0003_arduino'),
	]

	operations = [
		migrations.AlterField(
			model_name='arduino',
			name='cadena',
			field=models.IntegerField(),
		),
	]
