# Generated by Django 2.0.7 on 2018-08-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('cond', '0004_auto_20180806_0454'),
	]

	operations = [
		migrations.AlterField(
			model_name='arduino',
			name='cadena',
			field=models.CharField(max_length=10),
		),
	]
