# Generated by Django 2.1.2 on 2019-09-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('cond', '0005_auto_20180810_0437'),
	]

	operations = [
		migrations.AlterField(
			model_name='user',
			name='cedula',
			field=models.IntegerField(null=True),
		),
	]
