# Generated by Django 2.1.2 on 2019-09-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('cond', '0006_auto_20190905_1121'),
	]

	operations = [
		migrations.AlterField(
			model_name='user',
			name='cedula',
			field=models.IntegerField(default=321),
			preserve_default=False,
		),
	]
