# Generated by Django 2.0.7 on 2019-09-16 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('cond', '0007_auto_20190905_1132'),
	]

	operations = [
		migrations.CreateModel(
			name='Recibos',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('recibourl', models.FilePathField(path='cond/static/cond/recibos')),
				('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
			],
		),
	]
