# Generated by Django 2.0.7 on 2019-09-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('cond', '0008_recibos'),
	]

	operations = [
		migrations.AlterField(
			model_name='user',
			name='cedula',
			field=models.IntegerField(null=True),
		),
	]
