# Generated by Django 2.0.7 on 2019-09-16 21:17

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('cond', '0009_auto_20190916_1714'),
	]

	operations = [
		migrations.AlterField(
			model_name='user',
			name='apartament',
			field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cond.Apartment'),
		),
		migrations.AlterField(
			model_name='user',
			name='telefono',
			field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True),
		),
	]
