# Generated by Django 2.1.2 on 2019-09-17 00:51

from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		('cond', '0010_auto_20190916_1717'),
	]

	operations = [
		migrations.RenameModel(
			old_name='Recibos',
			new_name='Recibo',
		),
	]
