# Generated by Django 2.1.2 on 2019-09-25 00:23

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('cond', '0011_auto_20190916_2051'),
	]

	operations = [
		migrations.CreateModel(
			name='Luces',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('parque', models.BooleanField()),
				('mesas', models.BooleanField()),
				('estacionamiento1', models.BooleanField()),
				('estacionamiento2', models.BooleanField()),
			],
		),
	]
