# Generated by Django 2.1.2 on 2019-10-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('cond', '0012_luces'),
	]

	operations = [
		migrations.CreateModel(
			name='Tanque',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('volumen', models.IntegerField()),
				('time', models.DateTimeField(auto_now_add=True)),
			],
		),
	]
