# Generated by Django 2.2.6 on 2019-10-31 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('cond', '0014_porton_reguser'),
	]

	operations = [
		migrations.AlterField(
			model_name='user',
			name='telefono',
			field=models.IntegerField(null=True),
		),
	]
