# Generated by Django 2.2.6 on 2019-10-31 04:32

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('cond', '0015_auto_20191030_2314'),
	]

	operations = [
		migrations.AlterField(
			model_name='user',
			name='telefono',
			field=models.CharField(max_length=20, null=True),
		),
	]
